// <auto-generated />
using System;
using System.Collections.Generic;
using GoldenGroupAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoldenGroupAPI.Migrations
{
    [DbContext(typeof(GoldenGroupDbContext))]
    partial class GoldenGroupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoldenGroupAPI.Models.BuyerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int>("Liquidity")
                        .HasColumnType("integer")
                        .HasColumnName("liquidity");

                    b.Property<int>("MaxFloor")
                        .HasColumnType("integer")
                        .HasColumnName("max_floor");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price");

                    b.Property<int>("MinFloor")
                        .HasColumnType("integer")
                        .HasColumnName("min_floor");

                    b.Property<double>("MinSize")
                        .HasColumnType("double precision")
                        .HasColumnName("min_size");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("request_type");

                    b.Property<int[]>("Zones")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("zones");

                    b.HasKey("Id")
                        .HasName("pk_buyer_request");

                    b.HasIndex("ClientId");

                    b.ToTable("buyer_request", (string)null);

                    b.HasDiscriminator<string>("RequestType").HasValue("BuyerRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<List<string>>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("phone_numbers");

                    b.HasKey("Id")
                        .HasName("pk_client");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.HousingUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<double>("Rooms")
                        .HasColumnType("double precision")
                        .HasColumnName("rooms");

                    b.Property<double>("SquaredMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("squared_meters");

                    b.HasKey("Id")
                        .HasName("pk_housing_unit");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_housing_unit_listing_id");

                    b.ToTable("housing_unit", (string)null);
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("application_date");

                    b.Property<string>("AptNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apt_number");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime>("EnteringDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entering_date");

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update_date");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("listing_type");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("PropertyState")
                        .HasColumnType("integer")
                        .HasColumnName("property_state");

                    b.Property<double>("Rooms")
                        .HasColumnType("double precision")
                        .HasColumnName("rooms");

                    b.Property<double>("SquaredMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("squared_meters");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<int>("Zone")
                        .HasColumnType("integer")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_listing");

                    b.HasIndex("ClientId");

                    b.ToTable("listing", (string)null);

                    b.HasDiscriminator<string>("ListingType").HasValue("Listing");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.NormalBuyerRequest", b =>
                {
                    b.HasBaseType("GoldenGroupAPI.Models.BuyerRequest");

                    b.ToTable("buyer_request", (string)null);

                    b.HasDiscriminator().HasValue("Normal");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.TaboBuyerRequest", b =>
                {
                    b.HasBaseType("GoldenGroupAPI.Models.BuyerRequest");

                    b.Property<int>("Community")
                        .HasColumnType("integer")
                        .HasColumnName("community");

                    b.Property<decimal>("MaxEquity")
                        .HasColumnType("numeric")
                        .HasColumnName("max_equity");

                    b.Property<int>("MaxPartners")
                        .HasColumnType("integer")
                        .HasColumnName("max_partners");

                    b.Property<int>("RegistrationType")
                        .HasColumnType("integer")
                        .HasColumnName("registration_type");

                    b.ToTable("buyer_request", (string)null);

                    b.HasDiscriminator().HasValue("Tabo");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.NormalListing", b =>
                {
                    b.HasBaseType("GoldenGroupAPI.Models.Listing");

                    b.ToTable("listing", (string)null);

                    b.HasDiscriminator().HasValue("Normal");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.TaboListing", b =>
                {
                    b.HasBaseType("GoldenGroupAPI.Models.Listing");

                    b.Property<int>("NumOfPartners")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_partners");

                    b.Property<int>("RegistrationType")
                        .HasColumnType("integer")
                        .HasColumnName("registration_type");

                    b.Property<decimal>("RequiredEquity")
                        .HasColumnType("numeric")
                        .HasColumnName("required_equity");

                    b.ToTable("listing", (string)null);

                    b.HasDiscriminator().HasValue("Tabo");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.BuyerRequest", b =>
                {
                    b.HasOne("GoldenGroupAPI.Models.Client", "Client")
                        .WithMany("BuyerRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_buyer_request_client_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.HousingUnit", b =>
                {
                    b.HasOne("GoldenGroupAPI.Models.Listing", null)
                        .WithMany("HousingUnits")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_housing_unit_listing_listing_id");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.Listing", b =>
                {
                    b.HasOne("GoldenGroupAPI.Models.Client", "Client")
                        .WithMany("Listings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_client_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.Client", b =>
                {
                    b.Navigation("BuyerRequests");

                    b.Navigation("Listings");
                });

            modelBuilder.Entity("GoldenGroupAPI.Models.Listing", b =>
                {
                    b.Navigation("HousingUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
